#!/usr/bin/env python3
"""
Utility to regenerate tests/tests_generated.lua from the historical Python
test suite. Only needed if you modify the old Python definitions.
"""

from __future__ import annotations

import argparse
import pathlib
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
PY_RUNNER = ROOT / "tests" / "run_tests.py"
OUT_FILE = ROOT / "tests" / "tests_generated.lua"


def load_python_tests() -> list[dict[str, Any]]:
    namespace: dict[str, Any] = {"__file__": str(PY_RUNNER)}
    code = compile(PY_RUNNER.read_text(), str(PY_RUNNER), "exec")
    exec(code, namespace)
    tests_func = namespace["tests"]
    return list(tests_func())


def escape_lua_string(data: bytes) -> str:
    parts: list[str] = ['"']
    for b in data:
        if b == 10:
            parts.append("\\n")
        elif b == 13:
            parts.append("\\r")
        elif b == 9:
            parts.append("\\t")
        elif b == 34:  # "
            parts.append('\\"')
        elif b == 92:  # \
            parts.append("\\\\")
        elif 32 <= b <= 126:
            parts.append(chr(b))
        else:
            parts.append("\\%03d" % b)
    parts.append('"')
    return "".join(parts)


def encode_value(value: Any, indent: int = 0) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (bytes, bytearray)):
        return escape_lua_string(bytes(value))
    if isinstance(value, str):
        return escape_lua_string(value.encode("utf-8"))
    if isinstance(value, (list, tuple)):
        if not value:
            return "{}"
        items = ",\n".join(
            " " * (indent + 4) + encode_value(v, indent + 4) for v in value
        )
        return "{\n%s\n%s}" % (items, " " * indent)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for key in value:
            lines.append(
                " " * (indent + 4)
                + f"{key} = {encode_value(value[key], indent + 4)},"
            )
        return "{\n%s\n%s}" % ("\n".join(lines), " " * indent)
    raise TypeError(f"Unsupported value type: {type(value)!r}")


def convert_tests(tests: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "-- This file is auto-generated by tests/convert_tests_to_lua.py",
        "return {",
    ]
    for t in tests:
        lines.append("    {")
        lines.append(f"        id = {encode_value(t['id'], 8)},")
        lines.append(f"        tokens = {encode_value(t['tokens'], 8)},")
        input_file = t.get("input_file")
        if input_file is not None:
            lines.append(f"        input_file = {encode_value(input_file, 8)},")
        stdin = t.get("stdin")
        if stdin is not None:
            lines.append(f"        stdin = {encode_value(stdin, 8)},")
        extra_args = t.get("extra_args")
        if extra_args:
            lines.append(f"        extra_args = {encode_value(extra_args, 8)},")
        expect = dict(t["expect"])
        lines.append(f"        expect = {encode_value(expect, 8)},")
        if t.get("slow"):
            lines.append("        slow = true,")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Convert Python tests to Lua table")
    ap.add_argument(
        "--output",
        default=str(OUT_FILE),
        help="Path to write the generated Lua tests",
    )
    args = ap.parse_args()

    tests = load_python_tests()
    lua_code = convert_tests(tests)
    pathlib.Path(args.output).write_text(lua_code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
